name: Deploy Spring Batch to Huawei

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build app with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t yasser86/spring-batch-example:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push yasser86/spring-batch-example:latest

      - name: SSH and redeploy on Huawei
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HUAWEI_VM_IP }}
          username: root
          key: ${{ secrets.HUAWEI_SSH_KEY }}
          script: |
            docker pull yasser86/spring-batch-example:latest
            docker stop springbatch-container || true
            docker rm springbatch-container || true
            docker run -d -p 8081:8081 --restart unless-stopped --name springbatch-container yasser86/spring-batch-example:latest
